users:
  provider: database

providers:
  database:
    table: users
    class: App\AuthModule\Provider\DatabaseUserProvider
    #class: Keiryo\Security\Authentication\Provider\DatabaseUserProvider

login_field: email
login_path: '/login'