strategies:
  web: Simplex\Strategy\WebStrategy
  api: Simplex\Strategy\ApiStrategy

middlewares:
  global:
    - Simplex\Middleware\ErrorHandlerMiddleware
    - Simplex\Middleware\RoutingMiddleware
  web:
    - Simplex\Middleware\TrailingSlashMiddleware
    - Simplex\Middleware\ValidationErrorsMiddleware
    - Simplex\Middleware\AddCookiesToResponseMiddleware
    - Simplex\Http\Session\SessionMiddleware
    - Simplex\Middleware\CsrfTokenMiddleware
    - Simplex\Middleware\TwigSessionMiddleware
  api:
    - Simplex\Middleware\ApiTokenAuthenticationMiddleware
    - Simplex\Middleware\ParseJsonRequestBodyMiddleware
