jobeet_home:
  path: /
  controller: App\JobeetModule\Actions\JobShowAction:all

category_show:
  path: /category/{slug}
  controller: App\JobeetModule\Actions\CategoryShowAction:single
  requirements:
    slug: '[a-z0-9-]+'

job:
  resource: routes/jobs.yml
  name_prefix: job_
  prefix: /job

affiliate:
  resource: routes/affiliates.yml
  name_prefix: affiliate_
  prefix: /affiliate

api:
  resource: routes/api.yml
  name_prefix: api_
  prefix: /api
  trailing_slash_on_root: false
  defaults:
    _strategy: api